import type { Metadata } from "next";
import localFont from "next/font/local";
import { GoogleOAuthProvider } from '@react-oauth/google';
import "./globals.css";
import toast, { Toaster } from 'react-hot-toast';
import Provider from "./Provider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
        <GoogleOAuthProvider clientId="193245384182-dnolpspo4in24dnqveaemh7kcv42dktc.apps.googleusercontent.com">
     
      
     {children}
   
     <Toaster />
   </GoogleOAuthProvider>

        </Provider>
     
      </body>
    </html>
  );
}
